### ISSUE TITLE
Heartbeat and Sleep API being update

### ISSUE THREAD

**Issue by ranrinc** [vmanuel/hacs-google-fit#10]
As of this month API for Sleep and Heartbeat is being updated. So we get no reading on those API

https://developers.google.com/fit/improvements

**Comment by bbcorp** [comment]
Any update on this ?
Heartbeat and sleep aren't working

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
