### ISSUE TITLE
Feature request: Multiple Fit accounts

### ISSUE THREAD

**Issue by wasyl00** [vmanuel/hacs-google-fit#14]
Great work with the integration. Would love to see ability to add more then one account. So far I'm successful with doing it the dirty way by multiplying integrating and renaming it to google fit 2 but its a headache to update.

**Comment by hudsonbrendon** [comment]
> Great work with the integration. Would love to see ability to add more then one account. So far I'm successful with doing it the dirty way by multiplying integrating and renaming it to google fit 2 but its a headache to update.

Hi, I have the same problem, can you describe how you did it?

**Comment by wasyl00** [comment]
> > Great work with the integration. Would love to see ability to add more then one account. So far I'm successful with doing it the dirty way by multiplying integrating and renaming it to google fit 2 but its a headache to update.
> 
> Hi, I have the same problem, can you describe how you did it?

1. Copied Google_fit folder in /config/custom_components and multiplied integration by renaming it to Google_fit2
2. In manifest.json I changed to below:

` "domain": "google_fit2",
  "name": "Google Fit 2",`

3. In sensor.py I changed the below:
`SENSOR = 'google_fit2'`

The in config you have to add another sensor for - platform: google_fit2

**Comment by ranrinc** [comment]
yeah this is something that I also required so my wife can gather her information too.

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
