### ISSUE TITLE
Sensors don't respect HA unit_system settings

### ISSUE THREAD

**Issue by rpitera** [vmanuel/hacs-google-fit#4]
Is there any way to change the measurement units from metric to imperial for us 'freedom unit' impaired folks?  I'm sure it could be done with templates, but it seems like the sensor should use the HA unit_system setting.

Or is this a limitation of the API?

**Comment by tomshaffner** [comment]
Fyi, while it's not a real fix to your issue (e.g. not based on the HS unit_system settings and such and only addresses weight), the pull request I just submitted splits the weight sensor out to a KG and an LBS version. https://github.com/vmanuel/hacs-google-fit/pull/8. Was enough to cover the need for my use case; maybe is yours as well.

**Comment by rpitera** [comment]
> Fyi, while it's not a real fix to your issue (e.g. not based on the HS unit_system settings and such and only addresses weight), the pull request I just submitted splits the weight sensor out to a KG and an LBS version. #8. Was enough to cover the need for my use case; maybe is yours as well.

Thanks!  I'll check it out.

**Comment by tomshaffner** [comment]
And once more; I decided I wanted Miles instead of KM too, so added that split to the pull request.

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
