### ISSUE TITLE
Directory structure not HACS compliant

### ISSUE THREAD

**Issue by chbndrhnns** [vmanuel/hacs-google-fit#5]
I tried to add your repo as a custom URL in HACS and see this message:

```
An error ocoured while processing
Exception: HacsException
Message: Repostitory structure for master is not compliant
Could not add this repository, make sure it is compliant with HACS.
```

Is your repo meant to be added to HACS?

**Comment by Beaker1969** [comment]
@chbndrhnns 

I was able to get the repo in to HACS by setting as an  intergration.

Hope this helps.

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
