### ISSUE TITLE
Sleep is not being read

### ISSUE THREAD

**Issue by ranrinc** [vmanuel/hacs-google-fit#6]
Unsure what happens but sleep sensor is now 100% not working anymore. Is this a bugs or maybe Google change its API?

**Comment by asifma** [comment]
Can confirm this as well.....The Attributes are missing. Change in the API?

**Comment by ranrinc** [comment]
@asifma well in my case because original miband software does not doing a good job synchronize to Google Fit. The solutions (yes need to pay) is to replace your miband apps with notify and fitness for miband. Once you have the app running you will surely get the sync working 100% there are some bugs in sleep info though at the moment (hope will be fixed soon)

![photo6145242403028707983](https://user-images.githubusercontent.com/15801696/80555080-6013e500-89f9-11ea-8a2a-a92bdf06d2f0.jpg)

![photo6145568098988697824](https://user-images.githubusercontent.com/15801696/80555155-a1a49000-89f9-11ea-8f9c-7b9230448bb8.jpg)
as you can see the sleep info sync correctly now

**Comment by chintito4ever** [comment]
I see my sleep is being synced in Google Fit app but it is not being sent to Home Assistant, why's that?

**Comment by ranrinc** [comment]
Google Fit is changing API for sleep and heartrate so we need some changes on the script too..

https://developers.google.com/fit/improvements

**Comment by bbcorp** [comment]
Any update on sleep sensors ?

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
