### ISSUE TITLE
Feature request: blood pressure

### ISSUE THREAD

**Issue by BasTijs** [vmanuel/hacs-google-fit#9]
Can you extend the code with reading blood pressure from google fit? Im syncing data from Omron to google fit so that I can log it in HA.

There are also more measurements which may be interesting to add considering new smartwatches that can log blood oxygen.

**Comment by jherby2k** [comment]
Blood pressure - yes please!

**Comment by cheard** [comment]
This should be addressed in PR #18 

Let me know if it works for you!

**Comment by vmanuel** [comment]
I have not maintained this repository for a long time. I think the HACS from https://github.com/YorkshireIoT/ha-google-fit is perfect
